### ISSUE TITLE
More information for TAP output

### ISSUE THREAD

**Issue by tmysik** [sebastianbergmann/phpunit#2096]
In NetBeans, we support PHPUnit and currently use the JUNIT XML log format which is perfectly fine for us and contains all the information we need. However, to be able to display continuous test results we would like to start using the TAP output/format. Unfortunately, we would need more information about the tests, expecially if they fail - in which files they can be found, on which line, stack trace etc.

For example, the following output:
```
TAP version 13
ok 1 - CalculatorTest::testPlus
not ok 2 - Failure: CalculatorTest::testPlus2
  ---
  message: 'Failed asserting that 2 matches expected 1.'
  severity: fail
  data:
      got: 2
      expected: 1
  ...
ok 3 - CalculatorTest::testPlus3
ok 4 - CalculatorTest::testPlus4
not ok 5 - Error: CalculatorTest::testMinus
```
could be ideally improved to this one (using `#` in TAP output is OK  for comment):
```
TAP version 13
ok 1 - CalculatorTest::testPlus
# /home/joe/myproject/tests/CalculatorTest.php:50
not ok 2 - Failure: CalculatorTest::testPlus2
# /home/joe/myproject/tests/CalculatorTest.php:60
  ---
  message: 'Failed asserting that 2 matches expected 1.'
  severity: fail
  data:
      got: 2
      expected: 1
  ...
# stack trace:
# /home/joe/myproject/tests/CalculatorTestBase.php:100
# /home/joe/myproject/tests/CalculatorTest.php:65
ok 3 - CalculatorTest::testPlus3
# /home/joe/myproject/tests/CalculatorTest.php:70
ok 4 - CalculatorTest::testPlus4
# /home/joe/myproject/tests/CalculatorTest.php:80
not ok 5 - Error: CalculatorTest::testMinus
# /home/joe/myproject/tests/CalculatorTest.php:90
# stack trace:
# in /home/joe/myproject/tests/CalculatorTestBase.php:100
# in /home/joe/myproject/tests/CalculatorTest.php:95
```

It would be perfectly OK for us to show this extended information only if e.g. `--debug` CLI parameter is used.

Thanks in advance for your cooperation.
