### ISSUE TITLE
TravisCI, HHVM, PHPUnit

### ISSUE THREAD

**Issue by rquadling** [sebastianbergmann/phpunit#2235]
Hi.

I'm trying to get RobMorgan\Phinx to pass tests for HHVM.

Using `composer.json` with
```json
    "require-dev": {
        "phpunit/phpunit": "^4.8.26|^5.0"
    },
```

and a `before_script` of

```
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source --prefer-stable --prefer-lowest
```

As a consequence when TravisCI runs this setup (https://travis-ci.org/robmorgan/phinx/builds/142269927), I get all versions of PHP (5.4/5.5/5.6/7) passing with no warnings, but a fail for HHVM : https://travis-ci.org/robmorgan/phinx/jobs/142269932#L302

HHVM would SEEM to require a higher version of the `phpunit/php-token-stream` library than the one installed. V1.3.0 is installed, but requires V1.4.3 to have the missing token.

As `phpunit/phpunit` requires `phpunit/php-code-coverage` which requires `phpunit/php-token-stream`, somewhere in this chain, some sort of minimum support is needed for HHVM.

I've no idea how to solve this as (from I can see), composer doesn't allow package versions per php versions. So unless `phpunit/php-token-stream#v1.4.3` is made PHP7|hhvm minimum (which I don't think is feasible either), then I can see no way to get hhvm to pass unit tests AND support PHP5.4+

Not unless I don't use minimum versions and then upgrade all the tests to `phpunit/phpunit` V5+

Any suggestions (other than upgrade my tests) would be appreciated. The tests WILL be upgraded, but not anytime soon.

**Comment by rquadling** [comment]
My solution is to use a matrix build.

```
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - COMPOSER_FLAGS=--prefer-lowest

matrix:
  exclude:
    - php: hhvm
      env: COMPOSER_FLAGS=--prefer-lowest
  include:
    - php: hhvm
      env: COMPOSER_FLAGS=

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source --prefer-stable ${COMPOSER_FLAGS}
    - mysql -e 'create database phinx_testing;'
    - psql -c 'create database phinx_testing;' -U postgres
```

This results in 4 builds, with only the hhvm build NOT using `--prefer-lowest` which, for the time being is fine.

There are warnings about a deprecated method (`getMock()`), but that is solvable.

So. No longer an issue, but hopefully useful to others trying to support HHVM with PHP 5.4+ on Travis.

Of course, if I've missed something obvious, please let me know!
