### ISSUE TITLE
Call to undefined method SebastianBergmann\Environment\Runtime::discardsComments()

### ISSUE THREAD

**Issue by bscheshirwork** [sebastianbergmann/phpunit#2878]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.2.4
| PHP version         | 7.1.11
| Installation Method | Composer [into Docker Image](https://hub.docker.com/r/bscheshir/codeception/)

I try to create local test environment for [yii2 framework](https://github.com/yiisoft/yii2) based on docker image. I create fresh image; I use composition below. PHPUnit installation is a composer package.
```yml
# Local run unit tests
# for docker-compose CLI like this manual https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/
# run directly:
# docker-compose -f ../yii2-phpunit-docker-composition.yml run --rm --entrypoint bash php
# and run `composer install` before first time use
version: '2'
services:
  php:
    image: bscheshir/codeception:php7.1.11-fpm-yii2 #contain phpunit
    volumes:
      - ./yii2:/var/www/html #src and tests shared to container
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
    depends_on:
      - pgsql
# example for pgsql
# also add ./tests/data/config.local.php
# <?php
# $config['databases']['pgsql']['dsn'] = 'pgsql:host=pgsql;port=5432;dbname=yii2advanced';
# $config['databases']['pgsql']['username'] = 'yii2advanced';
# $config['databases']['pgsql']['password'] = 'yii2advanced';
  pgsql:
    image: postgres:10.1
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: yii2advanced
      POSTGRES_DB: yii2advanced
      POSTGRES_USER: yii2advanced
```
I install dependences of test code.
```sh
docker-compose -f ../yii2-phpunit-docker-composition.yml run --rm --entrypoint composer php install -vvv
```

I run it throw IDE
I have a error
```sh
docker-compose://[/home/dev/projects/yii2-phpunit-docker-composition.yml]:php/php /repo/vendor/phpunit/phpunit/phpunit --configuration /var/www/html/phpunit.xml.dist --teamcity
Testing started at 15:45 ...
PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Fatal error: Uncaught Error: Call to undefined method SebastianBergmann\Environment\Runtime::discardsComments() in /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 332

Error: Call to undefined method SebastianBergmann\Environment\Runtime::discardsComments() in /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 332

Call Stack:
    0.0003     357360   1. {main}() /repo/vendor/phpunit/phpunit/phpunit:0
    0.0111    1426544   2. PHPUnit\TextUI\Command::main() /repo/vendor/phpunit/phpunit/phpunit:53
    0.0111    1426656   3. PHPUnit\TextUI\Command->run() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:141
    0.8079   40496488   4. PHPUnit\TextUI\TestRunner->doRun() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:212


Process finished with exit code 255
```

I try to run this directly. Same result
```sh
$ docker-compose -f ../yii2-phpunit-docker-composition.yml run --rm --entrypoint bash php 
root@ea948b2fde56:/var/www/html# /repo/vendor/phpunit/phpunit/phpunit 
PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Fatal error: Uncaught Error: Call to undefined method SebastianBergmann\Environment\Runtime::discardsComments() in /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 332

Error: Call to undefined method SebastianBergmann\Environment\Runtime::discardsComments() in /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 332

Call Stack:
    0.0002     358712   1. {main}() /repo/vendor/phpunit/phpunit/phpunit:0
    0.0094    1427896   2. PHPUnit\TextUI\Command::main() /repo/vendor/phpunit/phpunit/phpunit:53
    0.0094    1428008   3. PHPUnit\TextUI\Command->run() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:141
    0.6681   40452824   4. PHPUnit\TextUI\TestRunner->doRun() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:212

root@ea948b2fde56:/var/www/html# 

```
