### ISSUE TITLE
Enable dependency resolution by default

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3133]
* https://github.com/sebastianbergmann/phpunit/pull/3092
* 8fa2aff0793e896be20f3e85585c827bc5e60530

**Comment by epdenouden** [comment]
@sebastianbergmann implementing this atm :)

**Comment by epdenouden** [comment]
AppVeyor needs a little tweak for the newer PHPUnit:
```
This version of PHPUnit is supported on PHP 7.2 and PHP 7.3.
You are using PHP 7.1.11 (c:\php\7.1.11\php.exe).
```
Not sure how to fix this correctly. Guess it's set in `appveyor.yml` in the repo?
```
  matrix:
    - PHP_VERSION: '7.1.11'
      XDEBUG_VERSION: '2.5.5-7.1'
      DEPENDENCIES: '--prefer-lowest'
    - PHP_VERSION: '7.1.11'
      XDEBUG_VERSION: '2.5.5-7.1'
      DEPENDENCIES: ''
```
