### ISSUE TITLE
Windows CI does not run tests

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#4333]
Example: https://github.com/sebastianbergmann/phpunit/runs/815235702?check_suite_focus=true

```
Run ./phpunit --coverage-clover=coverage.xml
  ./phpunit --coverage-clover=coverage.xml
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    COMPOSER_ROOT_VERSION: 9.3-dev
    PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter
    PHP_INI_VALUES: assert.exception=1, zend.assertions=1
    COMPOSER_CACHE_DIR: ~\AppData\Local\Composer
```

That's it, no actual output from PHPUnit.
