### ISSUE TITLE
PhpUnit 11.5

### ISSUE THREAD

**Issue by ekonoval** [sebastianbergmann/phpunit#6226]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.5.21
| PHP version         | 8.3.19
| Installation Method | Composer

#### Summary

I have a really strange endless and useless output on some of my tests failure, which is not indicating what exactly is wrong. 

![Image](https://github.com/user-attachments/assets/e4da9048-e0ed-459b-80ae-6a0c202b6dad)

![Image](https://github.com/user-attachments/assets/41c8ddb5-c421-46c6-94af-5abf5cc2d546)

#### Current behavior

```
..................................................PHP Fatal error:  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonly class PHPUnit\Framework\TestStatus\Known in /app/vendor/phpunit/phpunit/src/Framework/TestStatus/Error.php on line 19
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known                                   
                                                                               
In Error.php line 19:
                                                                               
  Non-readonly class PHPUnit\Framework\TestStatus\Error cannot extend readonl  
  y class PHPUnit\Framework\TestStatus\Known   
```

Now I'm showing the issue from Gitlab tests job,
for some reason it works locally in this specific case, but I remember having the same problem locally as well.

![Image](https://github.com/user-attachments/assets/8fff473b-f803-4db9-b6ce-847e447b3f8d)

I used 10.5 before that, with the same version of PHP (8.3.10, 8.3.19) but have never had a similar issue.

I run it like this on Gitlab
```
        vendor/bin/phpunit \
          --colors \
          --stop-on-error \
          --configuration phpunit.gitlab.xml
```

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.5/phpunit.xsd"
  backupGlobals="false"
  backupStaticProperties="false"
  bootstrap="bootstrap/autoload.php"
  colors="true"
  displayDetailsOnTestsThatTriggerDeprecations="true"
  processIsolation="false"
  stopOnFailure="false"
  displayDetailsOnAllIssues="true"
>
  <source>
    <include>
      <directory suffix=".php">./app</directory>
    </include>
    <exclude>
      <directory suffix=".php">./app/Http/Controllers/Admin</directory>
    </exclude>
  </source>

  <coverage includeUncoveredFiles="false">
  </coverage>

  <testsuites>
    <testsuite name="Application Test Suite">
      <directory>./tests/</directory>
    </testsuite>
  </testsuites>

</phpunit>
```

And here is local docker conf
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/11.5/phpunit.xsd"
  backupGlobals="false"
  backupStaticProperties="false"
  bootstrap="bootstrap/autoload.php"
  colors="true"
  displayDetailsOnTestsThatTriggerDeprecations="true"
  processIsolation="false"
  stopOnFailure="false"
  displayDetailsOnAllIssues="true"
  cacheResult="true"
  cacheDirectory="storage"
>
  <testsuites>
    <testsuite name="Application Test Suite">
      <directory>./tests/</directory>
    </testsuite>
  </testsuites>
  <php>
    <ini name="error_reporting" value="E_ALL"/>
    <ini name="display_startup_errors" value="On"/>
    <ini name="display_errors" value="On"/>
  </php>
</phpunit>
```

I cannot find any useful info on the internet AI is not helping, please give me a hint

**Comment by sebastianbergmann** [comment]
It appears that you have different installations of PHPUnit mixed up.

For instance, you may have used Composer to install PHPUnit and have configured the autoloader generated by Composer as PHPUnit's bootstrap script but then you invoke PHPUnit using an executable other than `vendor/bin/phpunit`.

**Comment by ekonoval** [comment]
Thank you for the fast response, but with all respect, I don't think I have multiple phpunits...
Here is what `composer show` displays

```
composer show phpunit/phpunit
name     : phpunit/phpunit
descrip. : The PHP Unit Testing framework.
keywords : phpunit, testing, xunit
versions : * 11.5.21
released : 2025-05-21, last week
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : https://phpunit.de/
source   : [git] https://github.com/sebastianbergmann/phpunit.git d565e2cdc21a7db9dc6c399c1fc2083b8010f289
dist     : [zip] https://api.github.com/repos/sebastianbergmann/phpunit/zipball/d565e2cdc21a7db9dc6c399c1fc2083b8010f289 d565e2cdc21a7db9dc6c399c1fc2083b8010f289
path     : /var/www/html/vendor/phpunit/phpunit
names    : phpunit/phpunit

support
issues : https://github.com/sebastianbergmann/phpunit/issues
security : https://github.com/sebastianbergmann/phpunit/security/policy
source : https://github.com/sebastianbergmann/phpunit/tree/11.5.21

autoload
files
classmap
src/

requires
ext-dom *
ext-json *
ext-libxml *
ext-mbstring *
ext-xml *
ext-xmlwriter *
myclabs/deep-copy ^1.13.1
phar-io/manifest ^2.0.4
phar-io/version ^3.2.1
php >=8.2
phpunit/php-code-coverage ^11.0.9
phpunit/php-file-iterator ^5.1.0
phpunit/php-invoker ^5.0.1
phpunit/php-text-template ^4.0.1
phpunit/php-timer ^7.0.1
sebastian/cli-parser ^3.0.2
sebastian/code-unit ^3.0.3
sebastian/comparator ^6.3.1
sebastian/diff ^6.0.2
sebastian/environment ^7.2.1
sebastian/exporter ^6.3.0
sebastian/global-state ^7.0.2
sebastian/object-enumerator ^6.0.1
sebastian/type ^5.1.2
sebastian/version ^5.0.2
staabm/side-effects-detector ^1.0.5

suggests
ext-soap To be able to generate mocks based on WSDL files
```
And here is Gitlab CI job (shortened)
```
PHPUnit:
  stage: Test
  needs: ["Build"]
  image: ${DOCKER_REPOSITORY}:${DOCKER_TAG}
  services:
    - name: mysql:8.0.40
      alias: mysql-testing
      command: ["--default-authentication-plugin=mysql_native_password", "--sql_mode=ONLY_FULL_GROUP_BY"]
    - name: gcr.io/x-tech/x-dev/gcloud:latest
      alias: gcloud
    - name: gcr.io/x-tech/x-dev/mongo:5.0.14
      alias: mongo
  variables:
    GIT_STRATEGY: none
    APP_ENV: testing
  script:
    - until mariadb --connect-timeout=5 -h ${DB_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE}; do sleep 2; done;
    - mariadb --connect-timeout=5 -h ${DB_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} -e "SELECT @@sql_mode"

    - cd /app
    - cp .env.testing .env
    - bash tests/scripts/testing.sh --host=127.0.0.1
    - composer install
    ## generate public and private keys
    - php artisan passport:keys

    - |
      vendor/bin/phpunit \
        --colors \
        --stop-on-error \
        --configuration phpunit.gitlab.xml
```

and in CI job we can clearly see it's being run with `vendor/bin/phpunit`

![Image](https://github.com/user-attachments/assets/8053b6b9-e07f-4a59-bc87-a7665000fb6f)
